# Generated by Django 2.1.5 on 2019-01-30 15:04

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.apps import apps as django_apps


def send_post_migrate_signal(apps, schema_editor):
    app_config = django_apps.get_app_config('tasks_app')
    models.signals.post_migrate.send(
        sender=app_config,
        app_config=app_config,
        verbosity=2,
        interactive=False,
        using=schema_editor.connection.alias,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='My Task List', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks_app.TaskList')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tasks_app.TaskTag'),
        ),
        migrations.RunSQL("INSERT INTO tasks_app_tasktag (tag) VALUES ('dev'), ('test'), ('design'), ('marketing'), ('chore'), ('admin'), ('devops');", "DELETE FROM tasks_app_tasktag"),

        # This ensures standard CRUD permissions are created on our new models so we
        # can add them to our group
        migrations.RunPython(send_post_migrate_signal, migrations.RunPython.noop),
    ]
